# Generated by Django 5.0.4 on 2024-04-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jikan_anime_id', models.IntegerField()),
                ('image', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('episodes', models.IntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('scored_by', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('favorites', models.IntegerField(default=0)),
                ('synopsis', models.CharField()),
                ('background', models.CharField()),
                ('season', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('genres', models.ManyToManyField(to='api.genre')),
            ],
        ),
    ]
